### ISSUE TITLE
Support adding typeinfo to third-party types

### ISSUE THREAD

**Issue by ninkibah** [SylEze/miroir#2]
First, let me say, I really like your little library. The builder pattern is very clever, and simple!

I notice you have a `reflected` concept which only returns true if T has a type_info typedef in it.

However, the `miroir::type_info<T>` declaration doesn't need to be inside T. That should allow me to instanciate type_info on a third party class, whose declaration I can't change. 

Do you plan to add support for this?

**Comment by ghost** [comment]
Hello, thank you for your feedback !

What you mentionned is indeed an issue, we should be able to have introspection for 3rd party types.
I started to think about a solution but I still don't have something that I really like.

Do not hesitate to tell me if you have and want to give some ideas !

**Comment by ghost** [comment]
Hey, just implemented something regarding this issue.

Look at this [example](https://github.com/SylEze/miroir/blob/master/examples/reflect_3rdparty_types/src/main.cpp) !

It allows you to reflect a type outside its declaration.

I will close the issue for the moment even if I'm not really happy with the current API.
